/** BORRA LA BD EXISTENTE Y CREA UNA NUEVA**/
drop database calzados;
CREATE DATABASE calzados;
USE calzados;

CREATE TABLE tipo_usuarios (
  ID_TIPO_USUARIO int(11) NOT NULL PRIMARY KEY,
  NOMBRE_TIPO_USUARIO varchar(25) NOT NULL
) ENGINE=InnoDB ;

CREATE TABLE generos (
  ID_GENERO int(11) NOT NULL  PRIMARY KEY,
  NOMBRE_GENERO varchar(15) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE productos (
  ID_PRODUCTO int(11) NOT NULL PRIMARY KEY,
  NOMBRE_PRODUCTO varchar(25) NOT NULL,
  IMAGEN longblob NOT NULL,
  PRECIO int(11) NOT NULL,
  TALLA_MENOR VARCHAR(5) NOT NULL,
  TALLA_MAYOR VARCHAR(5) NOT NULL ,
  COLOR1 VARCHAR(10) NOT NULL,
  COLOR2 VARCHAR(10) NOT NULL,
  COLOR3 VARCHAR(10) NOT NULL,
  CANTIDAD int(11) NOT NULL,
  CANTIDAD_COMPRAS INT(5) NOT NULL,
  ID_GENERO_FK int NOT NULL,
  FOREIGN KEY (ID_GENERO_FK) REFERENCES generos(ID_GENERO)
  on update no action
  on delete no action
) ENGINE=InnoDB ;

CREATE TABLE usuarios (
IDENTIFICACION VARCHAR(20) NOT NULL PRIMARY KEY,
  ID_USUARIO int(11) NOT NULL,
  PRIMER_NOMBRE varchar(15) NOT NULL,
  SEGUNDO_NOMBRE varchar(15) DEFAULT NULL,
  PRIMER_APELLIDO varchar(15) NOT NULL,
  SEGUNDO_APELLIDO varchar(15) NOT NULL,
  CORRE varchar(45) DEFAULT NULL,
  CLAVE varchar(20) NOT NULL,
  DIRECCION varchar(30) NOT NULL,
  TELEFONO int(11) NOT NULL,
  ID_TIPO_USUARIO_FK int(11) NOT NULL,
  ID_GENERO_FK int(11) NOT NULL,
  FOREIGN KEY (ID_TIPO_USUARIO_FK) REFERENCES tipo_usuarios(ID_TIPO_USUARIO),
  FOREIGN KEY (ID_GENERO_FK) REFERENCES generos(ID_GENERO)
  on update no action
  on delete no action
) ENGINE=InnoDB;

CREATE TABLE encabezado_ventas(
  NRO_FACTURA int(11) NOT NULL PRIMARY KEY,
  FECHA_COMPRA date NOT NULL,
  IDENTIFICACION_FK VARCHAR(20) NOT NULL,
  FOREIGN KEY (IDENTIFICACION_FK) REFERENCES usuarios(IDENTIFICACION)
  on update no action
  on delete no action
) ENGINE=InnoDB;


CREATE TABLE detalle_compras (
  ID_COMPRA int(11) NOT NULL PRIMARY KEY,
  CANTIDAD int(11) NOT NULL,
  TOTAL int(11) DEFAULT NULL,
  TALLAS varchar(5) DEFAULT NULL,
  pagado int(2) NOT NULL,
  ID_PRODUCTO_FK int(11) NOT NULL,
  NRO_FACTURA_FK int(11) NOT NULL,
  FOREIGN KEY (NRO_FACTURA_FK) REFERENCES encabezado_ventas(NRO_FACTURA),
  FOREIGN KEY (ID_PRODUCTO_FK) REFERENCES productos(ID_PRODUCTO)
  on update no action
  on delete no action
) ENGINE=InnoDB;



/*Generos de Los productos y de los usuarios*/
INSERT INTO generos(ID_GENERO,NOMBRE_GENERO) 
VALUES 
(1 , 'hombre'),
(2, 'mujer'),
(3, 'mujer y hombre');

/*Tipos de usuarios*/
INSERT INTO tipo_usuarios(ID_TIPO_USUARIO,NOMBRE_TIPO_USUARIO) 
VALUES
(1, 'administrador'),
(2,'cliente');

